#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker123"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "6ef7721619cb41c4bdc15b4ba20058d4" }
]
